// Code generated by mockery 2.52.3. DO NOT EDIT.

package postgre

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockpgPool is an autogenerated mock type for the pgPool type
type MockpgPool struct {
	mock.Mock
}

type MockpgPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockpgPool) EXPECT() *MockpgPool_Expecter {
	return &MockpgPool_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *MockpgPool) BeginTx(ctx context.Context, opts pgx.TxOptions) (pgx.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockpgPool_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockpgPool_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts pgx.TxOptions
func (_e *MockpgPool_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockpgPool_BeginTx_Call {
	return &MockpgPool_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockpgPool_BeginTx_Call) Run(run func(ctx context.Context, opts pgx.TxOptions)) *MockpgPool_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.TxOptions))
	})
	return _c
}

func (_c *MockpgPool_BeginTx_Call) Return(_a0 pgx.Tx, _a1 error) *MockpgPool_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockpgPool_BeginTx_Call) RunAndReturn(run func(context.Context, pgx.TxOptions) (pgx.Tx, error)) *MockpgPool_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockpgPool creates a new instance of MockpgPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockpgPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockpgPool {
	mock := &MockpgPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
