definitions:
  login.userLogin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  register.userRegister:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  response.ErrorResp:
    description: Error response information. with Error description and description
      what caused this. if Error was anwser always be "error".
    properties:
      anwser:
        type: string
    type: object
  response.OkResp:
    properties:
      anwser:
        type: string
    type: object
  user.User:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8082
info:
  contact: {}
  description: This is a auth service for my durak online.
  title: Swagger docs for auth durak
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user by email,password
      parameters:
      - description: Need only email and password
        in: body
        name: LoginData
        required: true
        schema:
          $ref: '#/definitions/login.userLogin'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResp'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResp'
      summary: login user
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registering user by email,username,password
      parameters:
      - description: need Email Username Password
        in: body
        name: RegisterData
        required: true
        schema:
          $ref: '#/definitions/register.userRegister'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.OkResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResp'
      summary: Register user
      tags:
      - Auth
swagger: "2.0"
